Update RUNC_VERSION in Dockerfile
awslabs/soci-snapshotter pull request #1096
Opened 2024-02-29 23:47 UTC by sondavidb

This addresses CVE-2024-21626

**Issue #, if available:**

**Description of changes:**

**Testing performed:**

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-01 20:57 UTC, turan18 approved these changes

2024-03-01 21:58 UTC, austinvazquez commented
Can we update the description that this updates runc in test infrastructure so it is clear that the CVE does not affect SOCI solution itself? My concern is the current wording may confuse users that SOCI is impacted by CVE 2024-21626

2024-03-01 21:59 UTC, austinvazquez requested changes
Can we update the description and commit message that this updates runc in test infrastructure so it is clear that the CVE does not affect SOCI solution itself? My concern is the current wording may confuse users that SOCI is impacted by CVE 2024-21626

2024-03-01 22:18 UTC, sondavidb commented
> Can we update the description and commit message that this updates runc in test infrastructure so it is clear that the CVE does not affect SOCI solution itself? My concern is the current wording may confuse users that SOCI is impacted by CVE 2024-21626 which it is not.

Done

2024-03-02 15:29 UTC, austinvazquez approved these changes

2024-03-04 19:07 UTC, sondavidb commented
Rebasing shenanigans, my bad 😓

2024-03-04 19:08 UTC, austinvazquez approved these changes

2024-03-04 19:22 UTC, turan18 approved these changes

2024-03-04 19:25 UTC, merged