Temporarily turn off the background fetch until it gets re-worked
awslabs/soci-snapshotter pull request #176
Opened 2022-11-09 16:50 UTC by vkuzniet

Signed-off-by: Viktor Kuznietsov <vkuzniet@amazon.com>

*Issue #, if available:*

*Description of changes:*
Temporarily turning off the background fetch until it gets re-worked. For more details see the issue https://github.com/awslabs/soci-snapshotter/issues/106

*Testing performed:*
- `make test && make check && make integration` pass
- Deployed `soci-snapshotter-grpc` and `soci` to an EC2 instance, created an index for rethinkdb and ran the container workload in lazy loading mode. Observed no log record referring to background fetcher.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-09 16:58 UTC, rdpsin approved these changes

2022-11-09 22:08 UTC, hanyuel requested changes
With this change, even when a user passes in NoBackgroundFetch=false in config parameter for running the snapshotter, the background fetch will not run.  I don’t think we should silently not run the bg fetch w/o any message when user explicitly sets the background fetch on. Sure the background fetch will be re-designed, but today it still can run. I suggest changing the behavior to not running the background fetch if no bg fetch config pass in from the user, and using the config from the user if provided.

2022-11-09 22:16 UTC, vkuzniet commented
> With this change, even when a user passes in NoBackgroundFetch=false in config parameter for running the snapshotter, the background fetch will not run. I don’t think we should silently not run the bg fetch w/o any message when user explicitly sets the background fetch on. Sure the background fetch will be re-designed, but today it still can run. I suggest changing the behavior to not running the background fetch if no bg fetch config pass in from the user, and using the config from the user if provided.

It is usually on by default. There's a config option to turn it off. The problem with intelligent handling there is that the `config.toml` is being deserialized into config struct and there's no way to know if the user set this field or it was set by default. 
If we agree that background fetcher as it is right now interferes with on-demand fetches, and it does seem so, then the easiest thing is to turn it off temporarily.

Another option would be to keep it disabled by default, e.g. name the option as `toml:background_fetch_enabled`, which will be set to false by default. In this case, the likelihood of someone enabling it would be much smaller.

2022-11-21 13:41 UTC, sbuckfelder commented
I'm comfortable with this

2022-11-21 13:41 UTC, sbuckfelder approved these changes

2022-11-21 20:33 UTC, closed without merging