Contrib/remove go multierror
awslabs/soci-snapshotter pull request #795
Opened 2023-08-19 09:02 UTC by manujgrover71

**Issue #, if available:**

Changes suggested in #793 

**Description of changes:**

- Using `errors.Join()` to join multiple errors together instead of using `mutlierror.Append()`
- Making sure `go-mutlierror` package is not present as direct dependancy in `go.mod` and `cmd/go.mod`

**Testing performed:**

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-21 16:08 UTC, Kern-- requested changes
Thanks for the contribution! 

The change looks good overall. Could you please squash your commits and add a sign off line to indicate that you are contributing under the project's Apache 2.0 license?

2023-08-21 16:58 UTC, manujgrover71 commented
Done

2023-08-21 17:43 UTC, Kern-- commented
Oh, looks like the signed off line isn't in the actual commit. You can add it with:
```
git commit --amend -s
```

This will add a line directly into your commit message like:
```
Signed-off-by: First Last <email@provider.com>
```

2023-08-21 20:33 UTC, Kern-- approved these changes

2023-08-22 19:48 UTC, turan18 approved these changes

2023-08-22 19:49 UTC, merged