[soci-snapshotter-grpc] Add containerd address as an option
awslabs/soci-snapshotter pull request #91
Opened 2022-10-04 10:24 UTC by sbuckfelder

*Description of changes:*
Adds an option to the **soci-snapshotter-grpc** to select the containerd server to use.  Follows existing convention.  This unblocks further manual and automated testing capabilities as it allows non-default instances of contained and soci-snapshotter-grpc to interact

*Testing performed:*
`make && make test && make integration`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-05 06:45 UTC, sbuckfelder commented on cmd/soci-snapshotter-grpc/main.go
> +	imageServiceAddress = flag.String("image-service-address", defaultImageServiceAddress, "address for the containerd server")
updated

2022-10-05 15:44 UTC, vkuzniet approved these changes

2022-10-06 20:25 UTC, Kern-- requested changes

2022-10-06 20:25 UTC, Kern-- commented on cmd/soci-snapshotter-grpc/main.go
> +	imageServiceAddress = flag.String("image-service-address", defaultImageServiceAddress, "address for the containerd server")
A couple points:

1) this is not the address of the containerd service, it's the address of the CRI image service which may or may not be the same as the containerd socket address. 
2) This shouldn't be a flag. This block is guarded by `config.CRIKeychainConfig.EnableKeychain` - this option should be in that same config `CRIKeychainConfig` object.

2022-10-10 18:12 UTC, sbuckfelder commented
As per Kern's recommendation, moved this to the config file

2022-10-10 18:12 UTC, closed without merging